# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OmhpA0LArDr76JpSqH-UGZgS7iu-PgLC
"""

!pip install transformers
# Import pipeline function
from transformers import pipeline

# Create emotion classifier
emotion_classifier = pipeline('text-classification', model='cardiffnlp/twitter-roberta-base-emotion',return_all_scores=True)

# Get scores for all 7 emotions
emotion_scores = emotion_classifier("I am so happy today", )

# Print scores
print(emotion_scores)

# Analyze a list of texts
texts = ["I am so happy today!", "I hate this weather!", "This is a surprise!"]

# Predict emotion
emotion_results = emotion_classifier(texts)
print(emotion_results)
# Output: [[{'label': 'JOY', 'score': 0.9832239747047424}], [{'label': 'ANGER', 'score': 0.9825204014778137}], [{'label': 'SURPRISE', 'score': 0.9874606728553772}]]

# Predict sentiment
sentiment_results = sentiment_classifier(texts)
print(sentiment_results)
# Output: [[{'label': 'POSITIVE', 'score': 0.9988501071929932}], [{'label': 'NEGATIVE', 'score': 0.9976886510848999}], [{'label': 'POSITIVE', 'score': 0.9832239747047424}]]